server:
  port: 6002

eureka:
  server:
    #关闭Eureka自我保护
    enable-self-preservation: false
  instance:
    hostname: eureka6002.com
  client:
    register-with-eureka: false #是否向注册中心注册自己
    fetch-registry: false #是否向注册中心获取注册信息
    service-url: #eureka服务器的地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
        defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - VMware.*  # 忽略虚拟机网卡
      use-only-site-local-interfaces: true
#      preferred-networks: 192.168.10.* # 优先使用 192.168.0.*

