server:
  port: 7002

spring:
  application:
    name: gateway
    zipkin:
      base-url: http://localhost:9411
    sluth:
      sampler:
        probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
          #UserMicroService
        - id: user-microservice_loginAndRegister_routh #usermicroservice-UserLoginAndRegisterController
          uri: lb://user-microservice
          predicates:
            - Path=/userlr/**

        - id: user-microservice-management_routh
          uri: lb://user-microservice
          predicates:
            - Path=/userm/**

          #ItemMicroService
        - id: item-microservice_routh
          uri: lb://item-microservice
          predicates:
            - Path=/item/**

          #OrderMicroService
        - id: order-microservice_routh
          uri: lb://order-microservice
          predicates:
            - Path=/order/**

          #PromoMicroService
        - id: promo-microservice_routh
          uri: lb://promo-microservice
          predicates:
            - Path=/promo/**

          #PaymentMicroService
        - id: payment-microservice_routh
          uri: lb://payment-microservice
          predicates:
            - Path=/payment/**

        - id: test
          uri: https://www.baidu.com
          predicates:
            - Path=/**

eureka:
  instance:
    instance-id: gateway7002
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:6001/eureka
        defaultZone: http://miaoshaProjectEurekaServer1.com:6001/eureka,http://miaoshaProjectEurekaServer2.com:6002/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

